---
- name: Test Event
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000
  rules:
  - name: test
    condition: 1 == 1
    action:
      run_job_template:
        name: Demo Job Template
        organization: Default
        job_args:
          limit: "{{ event.payload.hosts }}"
